# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alertbot_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 848)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 90, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 180, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 240, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 300, 67, 17))
        self.label_4.setObjectName("label_4")
        self.lineEdit_course = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_course.setGeometry(QtCore.QRect(190, 180, 231, 25))
        self.lineEdit_course.setObjectName("lineEdit_course")
        self.lineEdit_student = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_student.setGeometry(QtCore.QRect(190, 300, 221, 25))
        self.lineEdit_student.setObjectName("lineEdit_student")
        self.comboBox_student = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_student.setGeometry(QtCore.QRect(190, 240, 221, 25))
        self.comboBox_student.setObjectName("comboBox_student")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 360, 67, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(100, 400, 67, 17))
        self.label_6.setObjectName("label_6")
        self.comboBox_channel = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_channel.setGeometry(QtCore.QRect(180, 360, 221, 25))
        self.comboBox_channel.setObjectName("comboBox_channel")
        self.lineEdit_channel = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_channel.setGeometry(QtCore.QRect(180, 400, 221, 25))
        self.lineEdit_channel.setObjectName("lineEdit_channel")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(100, 460, 67, 17))
        self.label_7.setObjectName("label_7")
        self.radioButton_camera = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_camera.setGeometry(QtCore.QRect(100, 490, 112, 23))
        self.radioButton_camera.setObjectName("radioButton_camera")
        self.radioButton_rtsp = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_rtsp.setGeometry(QtCore.QRect(250, 490, 112, 23))
        self.radioButton_rtsp.setObjectName("radioButton_rtsp")
        self.radioButton_http = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_http.setGeometry(QtCore.QRect(440, 490, 112, 23))
        self.radioButton_http.setObjectName("radioButton_http")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(100, 560, 67, 17))
        self.label_8.setObjectName("label_8")
        self.lineEdit_source = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_source.setGeometry(QtCore.QRect(170, 560, 221, 25))
        self.lineEdit_source.setObjectName("lineEdit_source")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(100, 620, 67, 17))
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(470, 180, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_add_student = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_student.setGeometry(QtCore.QRect(460, 240, 89, 25))
        self.pushButton_add_student.setObjectName("pushButton_add_student")
        self.pushButton_add_channel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_channel.setGeometry(QtCore.QRect(470, 560, 89, 25))
        self.pushButton_add_channel.setObjectName("pushButton_add_channel")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(200, 620, 89, 25))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(330, 620, 89, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "智能巡邏 AlertBot"))
        self.label.setText(_translate("MainWindow", "智能巡邏  系統管理"))
        self.label_2.setText(_translate("MainWindow", "課程："))
        self.label_3.setText(_translate("MainWindow", "學生："))
        self.label_4.setText(_translate("MainWindow", "名稱："))
        self.label_5.setText(_translate("MainWindow", "頻道："))
        self.label_6.setText(_translate("MainWindow", "名稱："))
        self.label_7.setText(_translate("MainWindow", "影像擷取："))
        self.radioButton_camera.setText(_translate("MainWindow", "camera"))
        self.radioButton_rtsp.setText(_translate("MainWindow", "rtsp"))
        self.radioButton_http.setText(_translate("MainWindow", "http"))
        self.label_8.setText(_translate("MainWindow", "來源："))
        self.label_9.setText(_translate("MainWindow", "智能保全："))
        self.pushButton.setText(_translate("MainWindow", "設定"))
        self.pushButton_add_student.setText(_translate("MainWindow", "新增"))
        self.pushButton_add_channel.setText(_translate("MainWindow", "新增"))
        self.pushButton_start.setText(_translate("MainWindow", "新增"))
        self.pushButton_5.setText(_translate("MainWindow", "新增"))
